language: node_js

node_js:
  - "12.13.0"

cache: npm

os:
  - linux
  - osx

env:
  matrix:
    - NODE_VERSION="12"

matrix:
  fast_finish: true

install:
  - npm install
  - npm link

script:
  - npm test

after_success:
  - npm run calls
