# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

environment:
  matrix:
    - nodejs_version: "12"
      platform: x64
    - nodejs_version: "12"
      platform: x86

matrix:
  fast_finish: true

install:
  # Build
  - npm install
  - npm test

cache:
  # local npm modules
  - 'node_modules -> package.json'
  # npm cache
  - '%APPDATA%\npm-cache'

build: off

test: off

deploy: off
